### ISSUE TITLE
Minimum k-mer abundance threshold is undocumented & omitted from usage

### ISSUE THREAD

**Issue by bede** [dnbaker/dashing#16]
This feature is mentioned in this [very helpful reply](https://github.com/dnbaker/dashing/issues/14#issuecomment-458170799) to a now-closed issue, but is completely undocumented as far as I can tell.  

Usage of `dashing sketch -n 5` does not throw an error but also gives no feedback.

Application of a minimum abundance threshold is a very useful feature.

**Comment by dnbaker** [comment]
Hi! Thank you for pointing this out. I hadn't realized that it wasn't in the documentation.

I've added these in: https://github.com/dnbaker/dashing/commit/4aac0988af3334c650e5d62432ccfded29915cf2. Unfortunately, because of overlapping functionality, the usage menus for the separate subcommands don't entirely match.

**Comment by bede** [comment]
Thank you.

**Comment by bede** [comment]
Thanks for implementing this so quickly! I still don't find the usage wording especially clear, but it's enough.

`-n      Provide minimum expected count for fastq data. Default: -1 (passing all reads)`

**Comment by dnbaker** [comment]
Great feedback, as well. I've made this a little clearer in the usage. (`-n: Provide minimum expected count for fastq data. If unspecified, all kmers are passed.`) I'll close this for now, but feel free to reopen it if necessary.

Thanks again!
