### ISSUE TITLE
Updated releases

### ISSUE THREAD

**Issue by wwood** [dnbaker/dashing#56]
Hi,

For my machine it seems release/linux/dashing_s512 fails but dashing_s256, which I imagine is in line with my particular CPU. 

However, 
```
$ ./dashing_s256
Dashing version: v0.4.7-2-g6ad3
...
```
Which is a few versions behind, and also the bioconda package is out of date - any chance of an update on both fronts?
Thanks.

**Comment by dnbaker** [comment]
I've updated the binary releases as of https://github.com/dnbaker/dashing/commit/841be58ceff2e8907b65277989836a3af62db392, and I'm [working with bioconda](https://github.com/bioconda/bioconda-recipes/pull/24230) to get an updated version into conda, which is tricky because of the use of OpenMP for parallelization.

Because of the overlap with issue 41, I'll close this issue and merge this discussion into it.
